replicaCount: 1
namespace: minecraft
appName: minecraft

image:
  repository: itzg/minecraft-server
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 25565
  nodePort: 30023

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: minecraft.purplebelly.local
      paths:
        - /
  tls: []

persistence:
  enabled: true
  size: 10Gi

resources: {}
# e.g.
# limits:
#   cpu: 1000m
#   memory: 2Gi
# requests:
#   cpu: 500m
#   memory: 1Gi

eula: "true"

env:
  - name: EULA
    value: "true"
  - name: TYPE
    value: "FABRIC"
  - name: VERSION
    value: "1.21.7"
  - name: FABRIC_LOADER_VERSION
    value: "0.15.11" # Optional override if needed
  - name: REMOVE_OLD_MODS
    value: "TRUE"
  - name: MODS
    value: |
      https://edge.forgecdn.net/files/6713/285/journeymap-fabric-1.21.7-6.0.0-beta.52.jar

# runs PaperMC; other options: VANILLA, SPIGOT, FORGE, etc.
#env:
#  - name: EULA
#    value: "true"
#  - name: TYPE
#    value: "PAPER"
#  - name: VERSION
#    value: "1.21.7"
