replicaCount: 1
namespace: minecraft
appName: minecraft

image:
  repository: itzg/paper
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 25565

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: minecraft.purplebelly.local
      paths:
        - /
  tls: []

persistence:
  enabled: true
  size: 10Gi

resources: {}
# e.g.
# limits:
#   cpu: 1000m
#   memory: 2Gi
# requests:
#   cpu: 500m
#   memory: 1Gi

eula: "true"
