replicaCount: 1
namespace: minecraft
appName: minecraft-server

image:
  repository: itzg/minecraft-server
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 25565
  nodePort: 30023

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: minecraft.purplebelly.local
      paths:
        - /
  tls: []

persistence:
  enabled: true
  size: 50Gi

resources: {}
eula: "true"

env:
  - name: EULA
    value: "true"
  - name: ONLINE_MODE
    value: "false"
  - name: TYPE
    value: "NEOFORGE"
  - name: VERSION
    value: "1.21.7"
  - name: REMOVE_OLD_MODS
    value: "FALSE"
  - name: MODS
    value: |
      https://mediafilez.forgecdn.net/files/6733/601/corpse-neoforge-1.21.7-1.1.11.jar

# runs PaperMC; other options: VANILLA, SPIGOT, FORGE, etc.
