replicaCount: 1
namespace: minecraft
appName: minecraft

image:
  repository: itzg/minecraft-server
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 25565
  nodePort: 30023

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: minecraft.purplebelly.local
      paths:
        - /
  tls: []

persistence:
  enabled: true
  size: 10Gi

resources: {}
# e.g.
# limits:
#   cpu: 1000m
#   memory: 2Gi
# requests:
#   cpu: 500m
#   memory: 1Gi

eula: "true"

env:
  - name: EULA
    value: "true"       # must accept Mojang’s EULA
  - name: TYPE
    value: "PAPER"      # runs PaperMC; other options: VANILLA, SPIGOT, FORGE, etc.
  - name: VERSION
    value: "1.21.7"     # or “LATEST” to always pull the newest release
