apiVersion: v1
kind: PersistentVolume
metadata:
  name: etc-pihole
  namespace: pi-hole
spec:
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/network-utils/pihole/etc-pihole
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - purple-belly
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: etc-dnsmasq
  namespace: pi-hole
spec:
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/network-utils/pihole/etc-dnsmasq
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - purple-belly
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etc-pihole
  namespace: pi-hole
spec:
  volumeName: etc-pihole
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: local-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etc-dnsmasq
  namespace: pi-hole
spec:
  volumeName: etc-dnsmasq
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: local-storage
