namespace: emulatorjs
image:
  repository: docker.io/linuxserver/emulatorjs
  tag: latest@sha256:bc892148cee315125f48640f5a2b7ca6bd599967574424d71060c064e8a36a48

resources:
  limits:
    cpu: "1"
    memory: 500Mi
  requests:
    cpu: 500m
    memory: 250Mi

env:
  - name: DISABLE_IPFS
    value: "true"
  - name: S6_READ_ONLY_ROOT
    value: "1"
  - name: S6_YES_I_WANT_A_WORLD_WRITABLE_RUN_BECAUSE_KUBERNETES
    value: "1"

ingress:
  enabled: true
  host: games.purplebelly.local

persistence:
  size: 5Gi

config:
  retroarch: |
    input_menu_toggle_gamepad_combo = 3
    system_directory = /home/web_user/retroarch/system/
