apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      securityContext:
        fsGroup: 0
      containers:
        - name: pihole
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          ports:
            - containerPort: 53
              name: dns-tcp
              protocol: TCP
            - containerPort: 53
              name: dns-udp
              protocol: UDP
            - containerPort: 80
              name: web
          env:
            - name: TZ
              value: {{ .Values.timezone | quote }}
            - name: WEBPASSWORD
              value: {{ .Values.adminPassword | quote }}
            - name: DNS1
              value: "127.0.0.1#5335"
            - name: DNS2
              value: "127.0.0.1#5335"
          volumeMounts:
            - name: pihole-config
              mountPath: /etc/pihole
            - name: dnsmasq-config
              mountPath: /etc/dnsmasq.d
            - name: pihole-log
              mountPath: /var/log/pihole
            - name: lighttpd-log
              mountPath: /var/log/lighttpd
            - name: run-dir
              mountPath: /run
        - name: unbound
          image: mvance/unbound:latest
          volumeMounts:
            - mountPath: /etc/unbound
              name: unbound-config
          ports:
            - containerPort: 5335
              name: unbound
      volumes:
        - name: pihole-config
          persistentVolumeClaim:
            claimName: pihole-config-pvc
        - name: dnsmasq-config
          persistentVolumeClaim:
            claimName: dnsmasq-config-pvc
        - name: unbound-config
          configMap:
            name: unbound-config
        - name: pihole-log
          emptyDir: {}
        - name: lighttpd-log
          emptyDir: {}
        - name: run-dir
          emptyDir: {}
