apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      containers:
        - name: pihole
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
              name: web
            - containerPort: 53
              name: dns
          env:
            - name: TZ
              value: {{ .Values.timezone | quote }}
            - name: WEBPASSWORD
              value: {{ .Values.adminPassword | quote }}
