apiVersion: v1
kind: Service
metadata:
  name: pihole-web
spec:
  type: {{ .Values.serviceWeb.type }}
  selector:
    app: pihole
  ports:
    - port: {{ .Values.serviceWeb.port }}
      targetPort: 80
      name: http
