apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: llama
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:iovino/purplebelly.git
    targetRevision: HEAD
    path: charts/llama
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: llama
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
