apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: unbound
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:iovino/purplebelly.git
    targetRevision: HEAD
    path: charts/unbound
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: pi-hole
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
