apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-config
  namespace: {{ .Values.namespace }}
data:
  server.properties: |
    motd=Welcome to purplebelly!
    max-players=20
    online-mode=false
    level-name=world
