apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: mc
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["--noconsole"]
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: EULA
              value: "true"       # must accept Mojang’s EULA
            - name: TYPE
              value: "PAPER"      # runs PaperMC; other options: VANILLA, SPIGOT, FORGE, etc.
            - name: VERSION
              value: "1.21.7"     # or “LATEST” to always pull the newest release
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.appName }}-data
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
