apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-vip
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: kube-vip
    repoURL: https://kube-vip.github.io/helm-charts
    targetRevision: 0.6.4  # Match chart version, not image tag
    helm:
      valueFiles:
        - charts/deployments/kube-vip/values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
