apiVersion: v1
kind: ConfigMap
metadata:
  name: unbound-config
  namespace: pi-hole
data:
  unbound.conf: |
    server:
      # Use maximum verbosity for debugging
      verbosity: 5
      use-syslog: no

      # Basic server settings
      port: 5353
      interface: 0.0.0.0

      # Allow all access for debugging purposes
      access-control: 0.0.0.0/0 allow
