apiVersion: apps/v1
kind: Deployment
metadata:
  name: unbound
  namespace: pi-hole
  labels:
    app: unbound
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pi-hole
  strategy:
    # Uses Recreate to ensure the old pod is gone before the new one starts
    type: Recreate
  template:
    metadata:
      labels:
        app: unbound
    spec:
      containers:
        - image: mvance/unbound:latest
          name: unbound
          ports:
            - containerPort: 5353
              name: dns-udp
              protocol: UDP
            - containerPort: 5353
              name: dns-tcp
              protocol: TCP
          # Probes to check if unbound process is running and responsive
          startupProbe:
            exec:
              command: ["dig", "@127.0.0.1", "-p", "5353", "google.com"]
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 24 # Gives the container 2 minutes to start up
          livenessProbe:
            exec:
              command: ["dig", "@127.0.0.1", "-p", "5353", "google.com"]
            initialDelaySeconds: 15
            periodSeconds: 10
          volumeMounts:
            - mountPath: /etc/unbound/unbound.conf
              name: etc-unbound
              subPath: unbound.conf
      volumes:
        - name: etc-unbound
          configMap:
            name: unbound-config
