apiVersion: v1
kind: ConfigMap
metadata:
  name: emulatorjs-config
  namespace: emulatorjs
data:
  retroarch.cfg: |
    input_menu_toggle_gamepad_combo = 3
    system_directory = /home/web_user/retroarch/system/
