apiVersion: apps/v1
kind: Deployment
metadata:
  name: emulatorjs
  namespace: emulatorjs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emulatorjs
  template:
    metadata:
      labels:
        app: emulatorjs
    spec:
      containers:
        - name: emulatorjs
          image: "docker.io/linuxserver/emulatorjs@sha256:bc892148cee315125f48640f5a2b7ca6bd599967574424d71060c064e8a36a48"
          ports:
            - containerPort: 80
              name: emulatorjs
            - containerPort: 3000
              name: management
          resources:
            limits:
              cpu: "1"
              memory: 500Mi
            requests:
              cpu: 500m
              memory: 250Mi
          env:
            - name: DISABLE_IPFS
              value: "true"
            - name: S6_READ_ONLY_ROOT
              value: "1"
            - name: S6_YES_I_WANT_A_WORLD_WRITABLE_RUN_BECAUSE_KUBERNETES
              value: "1"
          volumeMounts:
            - name: config-volume
              mountPath: /config/profile/default/retroarch.cfg
              subPath: retroarch.cfg
              readOnly: true
            - name: roms
              mountPath: /data
      volumes:
        - name: config-volume
          configMap:
            name: emulatorjs-config
        - name: roms
          persistentVolumeClaim:
            claimName: emulatorjs-roms
