apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: emulatorjs
  namespace: emulatorjs
spec:
  ingressClassName: ingress-nginx
  rules:
    - host: games.purplebelly.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: emulatorjs
                port:
                  number: 80
