apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: llama-ingress
  namespace: llama
spec:
  ingressClassName: ingress-nginx
  rules:
    - host: llama.purplebelly.local
      http:
        paths:
          - backend:
              service:
                name: llama-server
                port:
                  number: 8080
            path: /
            pathType: Prefix
