apiVersion: v1
kind: Service
metadata:
  name: llama-server
  namespace: llama
  labels:
    app: llama-server
spec:
  ports:
    - name: llama-server
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8080
  selector:
    app: llama-server
  type: {{ .Values.service.type }}
